Repository searchspring/snap, pull requests merged in 2022-06, with the labels that each got.

#516 Readme Fix
  packages/snap-preact/README.md
Labels: critical

#517 Integration Documentation Updates
  assets/styles.css
  docs/DEBUGGING.md
  docs/INTEGRATION.md
  docs/INTEGRATION_BACKGROUND_FILTERS.md
  docs/INTEGRATION_CONTEXT.md
  docs/INTEGRATION_DEBUGGING.md
  docs/INTEGRATION_RECOMMENDATIONS.md
  docs/INTEGRATION_TRACKING.md
  docs/documents.js
  images/branch-override.png
  index.html
  packages/snap-toolbox/src/getContext/README.md
Labels: documentation, critical

#533 Recommendation fixes
  packages/snap-client/src/Client/apis/Recommend.test.ts
  packages/snap-client/src/Client/apis/Recommend.ts
  packages/snap-preact-components/src/components/Molecules/Carousel/Carousel.tsx
  packages/snap-preact-components/src/components/Organisms/Recommendation/Recommendation.tsx
  packages/snap-shared/src/MockData/MockData.ts
  packages/snap-shared/src/MockData/recommend/results/8uyt2m/ordered.json
Labels: bug, critical

#538 Branch Override Reload
  packages/snap-preact/src/Snap.tsx
Labels: bug, critical

#555 Carousel `threshold` Prop
  packages/snap-preact-components/src/components/Molecules/Carousel/Carousel.tsx
Labels: enhancement, critical
